#!/usr/bin/env bash
# Script that will display information about subdomains.

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type destination

    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        result=$(dig "${sub}.${domain}" +short)
        if [ -n "$result" ]; then
            record_type=$(dig "${sub}.${domain}" | awk '/ANSWER SECTION:/{getline; print $4}')
            destination=$(dig "${sub}.${domain}" | awk '/ANSWER SECTION:/{getline; print $5}')
            echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
        else
            echo "The subdomain ${sub} does not exist."
        fi
    done
}

if [ "$#" -eq 1 ]; then
    get_subdomain_info "$1"
elif [ "$#" -eq 2 ]; then
    get_subdomain_info "$1" "$2"
else
    echo "Invalid number of arguments. Please provide domain and optional subdomain."
fi
