#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1 
fi
scp -o StrictHostkeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP"
