#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "/listen 80 default_server/a \\\trewrite ^/redirect_me https://www.youtube.com;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a \\\terror_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n\tinternal;}" /etc/nginx/sites-available/default
host_server=$(hostname)
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $host_server;" /etc/nginx/sites-available/default
sudo service nginx restart
