#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
    frontend my_frontend
        bind *:80
        mode http
        default_backend my_backend

    backend my_backend
        mode http
        balance roundrobin
        server 284662-web-01 54.234.57.34:80 check
        server 284662-web-02 54.89.143.165:80 check
    " >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
# Restart HAProxy to apply changes
sudo service haproxy restart
