#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default Nginx configuration file from sites-enabled
rm /etc/nginx/sites-enabled/default

# Create a symbolic link from sites-available to sites-enabled for the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
