#!/usr/bin/env bash
#Displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=":" read -r user pass uid group info homedir shell;
do
    printf "The user %s is part of the %s gang, lives in %s " "$user" "$group" "$homedir"
    printf "and rides %s. %s's place is protected by the passcode %s, " "$shell" "$uid" "$pass"
    printf "more info about the user here: %s" "$info"
    printf "\n"
done < "/etc/passwd"
