#!/usr/bin/env bash
#Displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=":" read -r user pass uid group info homedir shell;
do
    echo "The user $user is part of the $group gang, lives in $homedir and rides $shell."
    echo "$uid's place is protected by the passcode $pass, more info about the user here: $info"
    echo
done < /etc/passwd
