#!/usr/bin/env bash
#Displays "Best School" 10 times, but for the 9th iteration,
#displays "Best School" and then "Hi" on a new line.
y=1
while [ $y -le 10 ]
do
    echo "Best School"
    if [ $y -eq 9 ]
    then
        echo "Hi"
    fi
    ((y++))
done
