#!/usr/bin/env bash
#Displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
y=1
while [ $y -le 20 ]
do
    case $y in
        4)
            echo $y
            echo "bad luck from China"
            ;;
        9)
            echo $y
            echo "bad luck from Japan"
            ;;
        17)
            echo $y
            echo "bad luck from Italy"
            ;;
        *)
            echo $y
            ;;
    esac
    ((y++))
done
