#!/usr/bin/env bash
# Your Bash script must be 7 lines long or less
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
su nginx -c "service nginx restart"
